#include "jnn01.h"

/* generated by fbt from .png files in images folder */
#include <jnn01_icons.h>

void jnn_app_menu_callback_main_menu(void* context, uint32_t index) {
    FURI_LOG_T(TAG, "jnn_app_menu_callback_main_menu");
    JnnApp* app = context;
    switch(index) {
    case JnnAppMenuSelection_One:
        scene_manager_handle_custom_event(app->scene_manager, JnnAppEvent_ShowPopup1);
        break;
    }
}

void jnn_app_scene_on_enter_main_menu(void* context) {
    FURI_LOG_T(TAG, "jnn_app_scene_on_enter_main_menu");
    JnnApp* app = context;
    menu_reset(app->menu);

    menu_add_item(
        app->menu,
        "Popup One",
        NULL,
        JnnAppMenuSelection_One,
        jnn_app_menu_callback_main_menu,
        app);
    view_dispatcher_switch_to_view(app->view_dispatcher, JnnAppView_Menu);
}

bool jnn_app_scene_on_event_main_menu(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "jnn_app_scene_on_event_main_menu");
    JnnApp* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case JnnAppEvent_ShowPopup1:
            scene_manager_next_scene(app->scene_manager, JnnAppScene_Popup1);
            consumed = true;
            break;
        }
        break;
    default:
        consumed = false;
        break;
    }
    return consumed;
}

void jnn_app_scene_on_exit_main_menu(void* context) {
    FURI_LOG_T(TAG, "jnn_app_scene_on_exit_main_menu");
    JnnApp* app = context;
    menu_reset(app->menu);
}

/* Popup 1 scene */
void jnn_app_scene_on_enter_popup_one(void* context) {
    FURI_LOG_T(TAG, "jnn_app_scene_on_enter_popup_one");
    JnnApp* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Popup One", 10, 10, AlignLeft, AlignTop);
    /* popup_set_icon(app->popup, 10, 10, ) */
    popup_set_text(app->popup, "Jnn Popup One!!", 20, 30, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, JnnAppView_Popup);
}

bool jnn_app_scene_on_event_popup_one(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "jnn_app_scene_on_event_popoup_one");
    UNUSED(context);
    UNUSED(event);
    return false;
}

void jnn_app_scene_on_exit_popup_one(void* context) {
    FURI_LOG_T(TAG, "jnn_app_scene_on_exit_popup_one");
    JnnApp* app = context;
    popup_reset(app->popup);
}

void (*const jnn_app_scene_on_enter_handlers[])(void*) = {
    jnn_app_scene_on_enter_main_menu,
    jnn_app_scene_on_enter_popup_one};

bool (*const jnn_app_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    jnn_app_scene_on_event_main_menu,
    jnn_app_scene_on_event_popup_one};

void (*const jnn_app_scene_on_exit_handlers[])(void*) = {
    jnn_app_scene_on_exit_main_menu,
    jnn_app_scene_on_exit_popup_one};

const SceneManagerHandlers jnn_app_scene_event_handlers = {
    .on_enter_handlers = jnn_app_scene_on_enter_handlers,
    .on_event_handlers = jnn_app_scene_on_event_handlers,
    .on_exit_handlers = jnn_app_scene_on_exit_handlers,
    .scene_num = JnnAppScene_count};

bool jnn_app_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FURI_LOG_T(TAG, "jnn_app_scene_manager_custom_event_callback");
    furi_assert(context);
    JnnApp* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

bool jnn_app_scene_manager_navigation_event_callback(void* context) {
    FURI_LOG_T(TAG, "jnn_app_scene_manager_navigation_event_callback");
    furi_assert(context);
    JnnApp* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

void jnn_app_scene_manager_init(JnnApp* app) {
    FURI_LOG_T(TAG, "jnn_app_scene_manager_init");
    app->scene_manager = scene_manager_alloc(&jnn_app_scene_event_handlers, app);
}

void jnn_app_view_dispatcher_init(JnnApp* app) {
    FURI_LOG_T(TAG, "jnn_app_view_dispatcher_init");
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_enable_queue(app->view_dispatcher);

    FURI_LOG_D(TAG, "jnn_app_view_dispatcher_init allocating views");
    app->menu = menu_alloc();
    app->popup = popup_alloc();

    FURI_LOG_D(TAG, "jnn_app_view_dispatcher_init setting callbacks");
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, jnn_app_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, jnn_app_scene_manager_navigation_event_callback);

    FURI_LOG_D(TAG, "jnn_app_view_dispatcher_init adding view menu");
    view_dispatcher_add_view(app->view_dispatcher, JnnAppView_Menu, menu_get_view(app->menu));

    FURI_LOG_D(TAG, "jnn_app_view_dispatcher_init adding view popup");
    view_dispatcher_add_view(app->view_dispatcher, JnnAppView_Popup, popup_get_view(app->popup));
}

JnnApp* jnn_app_init() {
    FURI_LOG_T(TAG, "jnn_app_init");
    JnnApp* app = malloc(sizeof(JnnApp));
    jnn_app_scene_manager_init(app);
    jnn_app_view_dispatcher_init(app);
    return app;
}

void jnn_app_free(JnnApp* app) {
    FURI_LOG_T(TAG, "jnn_app_free");
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, JnnAppView_Menu);
    view_dispatcher_remove_view(app->view_dispatcher, JnnAppView_Popup);
    view_dispatcher_free(app->view_dispatcher);
    menu_free(app->menu);
    popup_free(app->popup);
    free(app);
}

/* entry point */
int32_t jnn01_app(void* p) {
    UNUSED(p);
    FURI_LOG_I(TAG, "Jnn app launcher");
    JnnApp* app = jnn_app_init();
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, JnnAppScene_MainMenu);
    FURI_LOG_D(TAG, "Starting dispatcher...");
    view_dispatcher_run(app->view_dispatcher);

    FURI_LOG_I(TAG, "Jnn app finishing...");
    furi_record_close(RECORD_GUI);
    jnn_app_free(app);
    return 0;
}
