#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <jnn01_icons.h>

int32_t jnn01_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm jnn01!");

    return 0;
}
